#!/bin/bash

PDF=http://www.nctj.com/assets/library/document/l/original/latest_shorthand_results2.pdf
OUTFILE=someshittypdfthing.pdf
MD5FILE=hash.md5

curl ${PDF} --silent -o ${OUTFILE}

HASH=`md5 -q ${OUTFILE}`

if [ ! -e ${MD5FILE} ]
then
  echo "First run - I have no fucking way of knowing if anything changed"
else
  if [ `cat ${MD5FILE}` == ${HASH} ] 
  then
    echo "Nothing changed"
  else
    echo "Some shit changed"
  fi
fi

echo ${HASH} > ${MD5FILE}
rm ${OUTFILE}
